name: Handle Volunteer Dispatch

on:
  repository_dispatch:
    types: [volunteer_submission]

jobs:
  handle-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml clicksend-client

      - name: Debug - Show event payload
        run: |
          echo "Payload:"
          echo "${{ toJson(github.event.client_payload) }}"

      - name: Process volunteer submission
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: |
          python scripts/process_submission.py --payload-json "$PAYLOAD"

      - name: Regenerate calendar page
        run: |
          python scripts/generate_calendar.py

      - name: Commit updated files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add volunteer_input.yaml docs/calendar.html docs/volunteer_schedule.json
          git commit -m "Update volunteer data and calendar" || echo "No changes to commit"
          git push

      - name: Send SMS Notification (if opted in)
        if: ${{ github.event.client_payload.phone != '' && github.event.client_payload.notify_sms == 'true' }}
        env:
          CLICKSEND_USERNAME: ${{ secrets.CLICKSEND_USERNAME }}
          CLICKSEND_API_KEY: ${{ secrets.CLICKSEND_API_KEY }}
        run: |
          python scripts/send_sms.py "${{ github.event.client_payload.phone }}" "${{ github.event.client_payload.volunteer_name }}"
