name: Send Volunteer Shift Reminders

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml clicksend-client pytz

      - name: Send reminders
        env:
          CLICKSEND_USERNAME: ${{ secrets.CLICKSEND_USERNAME }}
          CLICKSEND_API_KEY: ${{ secrets.CLICKSEND_API_KEY }}
        run: python send_reminders.py
